services:
    Styla\CmsIntegration\EventSubscriber\StorefrontRequestControllerSubstituteEventSubscriber:
        arguments:
            - '@Styla\CmsIntegration\UseCase\StylaPagesInteractor'
            - '@Styla\CmsIntegration\Controller\Storefront\StylaPageController'
            - '@logger'
            - '@Shopware\Core\System\SystemConfig\SystemConfigService'
        tags:
            - { 'name': 'kernel.event_subscriber' }

    Styla\CmsIntegration\EventSubscriber\RestartConsumerAfterPluginConfigChangedEventSubscriber:
        arguments:
            - '@cache.messenger.restart_workers_signal'
        tags:
            - { 'name': 'kernel.event_subscriber' }
